config/routes.rb
Rails.application.routes.draw do
  get 'pages/two'
  get 'pages/three'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'pages#one'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def one
  end

  def two
  end

  def three
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FirstApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar-inverse">
      <%= link_to 'Pagina Uno', root_path%>
      <%= link_to 'Pagina Dos', pages_two_path%>
      <%= link_to 'Pagina Tres', pages_three_path%>
    </nav>
    <%= yield %>
  </body>
</html>

app/views/pages/one.html.erb
<h1>Simon Tomas Soto Squadrito</h1>

app/views/pages/three.html.erb
<h2>Soy un titulo de la Página 3</h2>
<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Eveniet harum culpa consequatur praesentium consequuntur ullam. Alias voluptate dolor nam quia ea, accusantium officia nihil consequuntur ratione labore doloribus doloremque amet.</p>

app/views/pages/two.html.erb
<%= image_tag "Captura.png"%>